# Generated by Django 4.2.4 on 2023-12-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonial_role_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_profile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.service'),
        ),
    ]
